-- return {
--     "tiagovla/tokyodark.nvim",
--     opts = {
--         -- custom options here
--     },
--     config = function(_, opts)
--         require("tokyodark").setup(opts) -- calling setup is optional
--         vim.cmd [[colorscheme tokyodark]]
--     end,
-- }
-- return {
--   {
--     "olimorris/onedarkpro.nvim",
--     priority = 1000, -- Ensure it loads first
--     lazy = false,    -- Load on startup
--     config = function()
--       vim.cmd("colorscheme onedark")
--     end,
--   },
-- }
-- Add a custom keybinding to toggle the colorscheme

return {
    "vague2k/vague.nvim",
    lazy = false,  -- make sure we load this during startup if it is your main colorscheme
    priority = 1000, -- make sure to load this before all the other plugins
    config = function()
        -- NOTE: you do not need to call setup if you don't want to.
        require("vague").setup({
            -- optional configuration here
        })
        vim.cmd("colorscheme vague")
    end
}
-- return {
--   {
--     "scottmckendry/cyberdream.nvim",
--     lazy = false,
--     priority = 1000,
--     config = function()
--       require("cyberdream").setup({
--         variant = "auto", -- needed for :CyberdreamToggleMode to work
--         -- All other options stay default
--         colors = {
--           green = "#00cc00", -- ✅ just darken the green slightly
--         },
--       })
--
--       vim.cmd("colorscheme cyberdream")
--
--       -- Toggle with <leader>tt
--       vim.keymap.set("n", "<leader>tt", ":CyberdreamToggleMode<CR>", { noremap = true, silent = true, desc = "Toggle Cyberdream Theme" })
--
--       -- Notify user on theme change
--       vim.api.nvim_create_autocmd("User", {
--         pattern = "CyberdreamToggleMode",
--         callback = function(event)
--           vim.notify("Switched to " .. (event.data or "unknown") .. " mode!", vim.log.levels.INFO, { title = "Cyberdream" })
--         end,
--       })
--     end,
--   },
-- }

-- somewhere in your config:

-- return {
-- 	"sainnhe/gruvbox-material",
-- 	lazy = false,
-- 	priority = 1000,
-- 	config = function()
-- 		-- optionally configure and load the colorscheme
-- 		-- directly inside the plugin declaration.
-- 		vim.g.gruvbox_material_enable_italic = true
-- 		vim.cmd.colorscheme("gruvbox-material")
-- 	end,
-- -- }
-- return {
-- 	{
-- 		"rose-pine/neovim",
-- 		name = "rose-pine",
-- 		config = function()
-- 			require("rose-pine").setup({
-- 				variant = "auto", -- auto, main, moon, or dawn
-- 				dark_variant = "main", -- main, moon, or dawn
-- 				dim_inactive_windows = false,
-- 				extend_background_behind_borders = true,
--
-- 				enable = {
-- 					terminal = true,
-- 					legacy_highlights = true, -- improve compatibility for previous versions of neovim
-- 					migrations = true, -- handle deprecated options automatically
-- 				},
--
-- 				styles = {
-- 					bold = true,
-- 					italic = true,
-- 					transparency = false,
-- 				},
--
-- 				groups = {
-- 					border = "muted",
-- 					link = "iris",
-- 					panel = "surface",
--
-- 					error = "love",
-- 					hint = "iris",
-- 					info = "foam",
-- 					note = "pine",
-- 					todo = "rose",
-- 					warn = "gold",
--
-- 					git_add = "foam",
-- 					git_change = "rose",
-- 					git_delete = "love",
-- 					git_dirty = "rose",
-- 					git_ignore = "muted",
-- 					git_merge = "iris",
-- 					git_rename = "pine",
-- 					git_stage = "iris",
-- 					git_text = "rose",
-- 					git_untracked = "subtle",
--
-- 					h1 = "iris",
-- 					h2 = "foam",
-- 					h3 = "rose",
-- 					h4 = "gold",
-- 					h5 = "pine",
-- 					h6 = "foam",
-- 				},
--
-- 				highlight_groups = {
-- 					-- comment = { fg = "foam" },
-- 					-- vertsplit = { fg = "muted", bg = "muted" },
-- 				},
--
-- 				before_highlight = function(group, highlight, palette)
-- 					-- disable all undercurls
-- 					-- if highlight.undercurl then
-- 					--     highlight.undercurl = false
-- 					-- end
-- 					--
-- 					-- change palette colour
-- 					-- if highlight.fg == palette.pine then
-- 					--     highlight.fg = palette.foam
-- 					-- end
-- 				end,
-- 			})
--
-- 			-- vim.cmd("colorscheme rose-pine")
-- 			-- uncomment one of the following to use a specific variant
-- 			vim.cmd("colorscheme rose-pine-main")
-- 			-- vim.cmd("colorscheme rose-pine-moon")
-- 			-- vim.cmd("colorscheme rose-pine-dawn")
-- 		end,
-- 	},
-- }
--
-- -- default options:
-- setup must be called before loadingr
-- return {
-- 	"mofiqul/vscode.nvim",
-- 	lazy = false,
-- 	priority = 1000,
-- 	config = function()
-- 		-- function to switch between light and dark themes
-- 		local function switch_vscode_theme()
-- 			if vim.o.background == "dark" then
-- 				vim.o.background = "light"
-- 				require("vscode").load("light")
-- 				print("switched to vscode light theme")
-- 			else
-- 				vim.o.background = "dark"
-- 				require("vscode").load("dark")
-- 				print("switched to vscode dark theme")
-- 			end
-- 		end
--
-- 		-- create a user command for switching themes
-- 		vim.api.nvim_create_user_command("Switchvscodetheme", switch_vscode_theme, {})
--
-- 		-- optionally set a keybinding for switching themes
-- 		vim.api.nvim_set_keymap("n", "<leader>kt", ":Switchvscodetheme<cr>", { noremap = true, silent = true })
--
-- 		-- load the initial theme
-- 		vim.o.background = "dark"
-- 		require("vscode").load("dark")
--
-- 		require("bufferline").setup({
-- 			options = {
-- 				buffer_close_icon = "",
-- 				close_command = "bdelete %d",
-- 				close_icon = "",
-- 				indicator = {
-- 					style = "icon",
-- 					icon = " ",
-- 				},
-- 				left_trunc_marker = "",
-- 				modified_icon = "●",
-- 				offsets = { { filetype = "nvimtree", text = "explorer", text_align = "center" } },
-- 				right_mouse_command = "bdelete! %d",
-- 				right_trunc_marker = "",
-- 				show_close_icon = false,
-- 				show_tab_indicators = true,
-- 			},
-- 			highlights = {
-- 				fill = {
-- 					fg = { attribute = "fg", highlight = "normal" },
-- 					bg = { attribute = "bg", highlight = "statuslinenc" },
-- 				},
-- 				background = {
-- 					fg = { attribute = "fg", highlight = "normal" },
-- 					bg = { attribute = "bg", highlight = "statusline" },
-- 				},
-- 				buffer_visible = {
-- 					fg = { attribute = "fg", highlight = "normal" },
-- 					bg = { attribute = "bg", highlight = "normal" },
-- 				},
-- 				buffer_selected = {
-- 					fg = { attribute = "fg", highlight = "normal" },
-- 					bg = { attribute = "bg", highlight = "normal" },
-- 				},
-- 				separator = {
-- 					fg = { attribute = "bg", highlight = "normal" },
-- 					bg = { attribute = "bg", highlight = "statusline" },
-- 				},
-- 				separator_selected = {
-- 					fg = { attribute = "fg", highlight = "special" },
-- 					bg = { attribute = "bg", highlight = "normal" },
-- 				},
-- 				separator_visible = {
-- 					fg = { attribute = "fg", highlight = "normal" },
-- 					bg = { attribute = "bg", highlight = "statuslinenc" },
-- 				},
-- 				close_button = {
-- 					fg = { attribute = "fg", highlight = "normal" },
-- 					bg = { attribute = "bg", highlight = "statusline" },
-- 				},
-- 				close_button_selected = {
-- 					fg = { attribute = "fg", highlight = "normal" },
-- 					bg = { attribute = "bg", highlight = "normal" },
-- 				},
-- 				close_button_visible = {
-- 					fg = { attribute = "fg", highlight = "normal" },
-- 					bg = { attribute = "bg", highlight = "normal" },
-- 				},
-- 			},
-- 		})
-- 	end,
-- }
-- --
-- return {
-- 	"olivercederborg/poimandres.nvim",
-- 	lazy = false,
-- 	priority = 1000,
-- 	config = function()
-- 		require("poimandres").setup({
-- 			-- leave this setup function empty for default config
-- 			-- or refer to the configuration section
-- 			-- for configuration options
-- 		})
-- 	end,
--
-- 	-- optionally set the colorscheme within lazy config
-- 	init = function()
-- 		vim.cmd("colorscheme poimandres")
-- 	end,
-- }


-- return {
--     {
--         "folke/tokyonight.nvim",
--         lazy = false,
--         priority = 1000,
--         opts = {},
--         config = function()
--             vim.cmd([[
-- colorscheme tokyonight-night
-- ]])
--         end,
--     },
-- }

-- return {
-- 	--
-- 	"oxfist/night-owl.nvim",
--
-- 	lazy = false, -- make sure we load this during startup if it is your main colorscheme
-- 	priority = 1000, -- make sure to load this before all the other start plugins
-- 	config = function()
-- 		-- load the colorscheme here
-- 		require("night-owl").setup()
-- 		vim.cmd.colorscheme("night-owl")
-- 	end,
-- }
-- function ColorMyPencils(color)
-- 	color = color or "rose-pine-moon"
-- 	vim.cmd.colorscheme(color)
--
-- 	vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
-- 	vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
-- end
--
-- return {
-- 	{
-- 		"erikbackman/brightburn.vim",
-- 	},
--
-- 	{
-- 		"ellisonleao/gruvbox.nvim",
-- 		name = "gruvbox",
-- 		config = function()
-- 			require("gruvbox").setup({
-- 				terminal_colors = true, -- add neovim terminal colors
-- 				undercurl = true,
-- 				underline = false,
-- 				bold = true,
-- 				italic = {
-- 					strings = false,
-- 					emphasis = false,
-- 					comments = false,
-- 					operators = false,
-- 					folds = false,
-- 				},
-- 				strikethrough = true,
-- 				invert_selection = false,
-- 				invert_signs = false,
-- 				invert_tabline = false,
-- 				invert_intend_guides = false,
-- 				inverse = true, -- invert background for search, diffs, statuslines and errors
-- 				contrast = "", -- can be "hard", "soft" or empty string
-- 				palette_overrides = {},
-- 				overrides = {},
-- 				dim_inactive = false,
-- 				transparent_mode = false,
-- 			})
-- 		end,
-- 	},
-- }

--
-- 	{
-- 		"rose-pine/neovim",
-- 		name = "rose-pine",
-- 		config = function()
-- 			require("rose-pine").setup({
-- 				disable_background = true,
-- 				styles = {
-- 					italic = false,
-- 				},
-- 			})
-- 			-- Uncomment this line if you want to set rose-pine as the color scheme
-- 			ColorMyPencils("rose-pine-moon")
-- 		end,
-- 	},
-- }
