-- return {
-- 	"sainnhe/gruvbox-material",
-- 	lazy = false,
-- 	priority = 1000,
-- 	config = function()
-- 		-- Optionally configure and load the colorscheme
-- 		-- directly inside the plugin declaration.
-- 		vim.g.gruvbox_material_enable_italic = true
-- 		vim.cmd.colorscheme("gruvbox-material")
-- 	end,
-- }
-- return {
-- 	{
-- 		"rose-pine/neovim",
-- 		name = "rose-pine",
-- 		config = function()
-- 			require("rose-pine").setup({
-- 				variant = "auto", -- auto, main, moon, or dawn
-- 				dark_variant = "main", -- main, moon, or dawn
-- 				dim_inactive_windows = false,
-- 				extend_background_behind_borders = true,
--
-- 				enable = {
-- 					terminal = true,
-- 					legacy_highlights = true, -- Improve compatibility for previous versions of Neovim
-- 					migrations = true, -- Handle deprecated options automatically
-- 				},
--
-- 				styles = {
-- 					bold = true,
-- 					italic = true,
-- 					transparency = false,
-- 				},
--
-- 				groups = {
-- 					border = "muted",
-- 					link = "iris",
-- 					panel = "surface",
--
-- 					error = "love",
-- 					hint = "iris",
-- 					info = "foam",
-- 					note = "pine",
-- 					todo = "rose",
-- 					warn = "gold",
--
-- 					git_add = "foam",
-- 					git_change = "rose",
-- 					git_delete = "love",
-- 					git_dirty = "rose",
-- 					git_ignore = "muted",
-- 					git_merge = "iris",
-- 					git_rename = "pine",
-- 					git_stage = "iris",
-- 					git_text = "rose",
-- 					git_untracked = "subtle",
--
-- 					h1 = "iris",
-- 					h2 = "foam",
-- 					h3 = "rose",
-- 					h4 = "gold",
-- 					h5 = "pine",
-- 					h6 = "foam",
-- 				},
--
-- 				highlight_groups = {
-- 					-- Comment = { fg = "foam" },
-- 					-- VertSplit = { fg = "muted", bg = "muted" },
-- 				},
--
-- 				before_highlight = function(group, highlight, palette)
-- 					-- Disable all undercurls
-- 					-- if highlight.undercurl then
-- 					--     highlight.undercurl = false
-- 					-- end
-- 					--
-- 					-- Change palette colour
-- 					-- if highlight.fg == palette.pine then
-- 					--     highlight.fg = palette.foam
-- 					-- end
-- 				end,
-- 			})
--
-- 			-- vim.cmd("colorscheme rose-pine")
-- 			-- Uncomment one of the following to use a specific variant
-- 			vim.cmd("colorscheme rose-pine-main")
-- 			-- vim.cmd("colorscheme rose-pine-moon")
-- 			-- vim.cmd("colorscheme rose-pine-dawn")
-- 		end,
-- 	},
-- }
--
-- -- Default options:
-- setup must be called before loadingr
-- return {
-- 	"Mofiqul/vscode.nvim",
-- 	lazy = false,
-- 	priority = 1000,
-- 	config = function()
-- 		-- Function to switch between light and dark themes
-- 		local function switch_vscode_theme()
-- 			if vim.o.background == "dark" then
-- 				vim.o.background = "light"
-- 				require("vscode").load("light")
-- 				print("Switched to vscode light theme")
-- 			else
-- 				vim.o.background = "dark"
-- 				require("vscode").load("dark")
-- 				print("Switched to vscode dark theme")
-- 			end
-- 		end
--
-- 		-- Create a user command for switching themes
-- 		vim.api.nvim_create_user_command("SwitchVscodeTheme", switch_vscode_theme, {})
--
-- 		-- Optionally set a keybinding for switching themes
-- 		vim.api.nvim_set_keymap("n", "<leader>kt", ":SwitchVscodeTheme<CR>", { noremap = true, silent = true })
--
-- 		-- Load the initial theme
-- 		vim.o.background = "dark"
-- 		require("vscode").load("dark")
--
-- 		-- Configure bufferline
-- 		-- require("bufferline").setup({
-- 		-- 	options = {
-- 		-- 		buffer_close_icon = "",
-- 		-- 		close_command = "bdelete %d",
-- 		-- 		close_icon = "",
-- 		-- 		indicator = {
-- 		-- 			style = "icon",
-- 		-- 			icon = " ",
-- 		-- 		},
-- 		-- 		left_trunc_marker = "",
-- 		-- 		modified_icon = "●",
-- 		-- 		offsets = { { filetype = "NvimTree", text = "EXPLORER", text_align = "center" } },
-- 		-- 		right_mouse_command = "bdelete! %d",
-- 		-- 		right_trunc_marker = "",
-- 		-- 		show_close_icon = false,
-- 		-- 		show_tab_indicators = true,
-- 		-- 	},
-- 		-- 	highlights = {
-- 		-- 		fill = {
-- 		-- 			fg = { attribute = "fg", highlight = "Normal" },
-- 		-- 			bg = { attribute = "bg", highlight = "StatusLineNC" },
-- 		-- 		},
-- 		-- 		background = {
-- 		-- 			fg = { attribute = "fg", highlight = "Normal" },
-- 		-- 			bg = { attribute = "bg", highlight = "StatusLine" },
-- 		-- 		},
-- 		-- 		buffer_visible = {
-- 		-- 			fg = { attribute = "fg", highlight = "Normal" },
-- 		-- 			bg = { attribute = "bg", highlight = "Normal" },
-- 		-- 		},
-- 		-- 		buffer_selected = {
-- 		-- 			fg = { attribute = "fg", highlight = "Normal" },
-- 		-- 			bg = { attribute = "bg", highlight = "Normal" },
-- 		-- 		},
-- 		-- 		separator = {
-- 		-- 			fg = { attribute = "bg", highlight = "Normal" },
-- 		-- 			bg = { attribute = "bg", highlight = "StatusLine" },
-- 		-- 		},
-- 		-- 		separator_selected = {
-- 		-- 			fg = { attribute = "fg", highlight = "Special" },
-- 		-- 			bg = { attribute = "bg", highlight = "Normal" },
-- 		-- 		},
-- 		-- 		separator_visible = {
-- 		-- 			fg = { attribute = "fg", highlight = "Normal" },
-- 		-- 			bg = { attribute = "bg", highlight = "StatusLineNC" },
-- 		-- 		},
-- 		-- 		close_button = {
-- 		-- 			fg = { attribute = "fg", highlight = "Normal" },
-- 		-- 			bg = { attribute = "bg", highlight = "StatusLine" },
-- 		-- 		},
-- 		-- 		close_button_selected = {
-- 		-- 			fg = { attribute = "fg", highlight = "Normal" },
-- 		-- 			bg = { attribute = "bg", highlight = "Normal" },
-- 		-- 		},
-- 		-- 		close_button_visible = {
-- 		-- 			fg = { attribute = "fg", highlight = "Normal" },
-- 		-- 			bg = { attribute = "bg", highlight = "Normal" },
-- 		-- 		},
-- 		-- 	},
-- 		-- })
-- 	end,
-- }
--
return {

	"olivercederborg/poimandres.nvim",
	lazy = false,
	priority = 1000,
	config = function()
		require("poimandres").setup({
			-- leave this setup function empty for default config
			-- or refer to the configuration section
			-- for configuration options
		})
	end,

	-- optionally set the colorscheme within lazy config
	init = function()
		vim.cmd("colorscheme poimandres")
	end,
}
--
-- return {
-- 	{
-- 		"folke/tokyonight.nvim",
-- 		priority = 1000, -- make sure to load this before all the other start plugins
-- 		config = function()
-- 			local bg = "#011628"
-- 			local bg_dark = "#011423"
-- 			local bg_highlight = "#143652"
-- 			local bg_search = "#0A64AC"
-- 			local bg_visual = "#275378"
-- 			local fg = "#CBE0F0"
-- 			local fg_dark = "#B4D0E9"
-- 			local fg_gutter = "#627E97"
-- 			local border = "#547998"
--
-- 			require("tokyonight").setup({
-- 				style = "night",
-- 				on_colors = function(colors)
-- 					colors.bg = bg
-- 					colors.bg_dark = bg_dark
-- 					colors.bg_float = bg_dark
-- 					colors.bg_highlight = bg_highlight
-- 					colors.bg_popup = bg_dark
-- 					colors.bg_search = bg_search
-- 					colors.bg_sidebar = bg_dark
-- 					colors.bg_statusline = bg_dark
-- 					colors.bg_visual = bg_visual
-- 					colors.border = border
-- 					colors.fg = fg
-- 					colors.fg_dark = fg_dark
-- 					colors.fg_float = fg
-- 					colors.fg_gutter = fg_gutter
-- 					colors.fg_sidebar = fg_dark
-- 				end,
-- 			})
-- 			-- load the colorscheme here
-- 			vim.cmd([[colorscheme tokyonight]])
-- 		end,
-- 	},
-- }
-- return {
-- 	--
-- 	"oxfist/night-owl.nvim",
--
-- 	lazy = false, -- make sure we load this during startup if it is your main colorscheme
-- 	priority = 1000, -- make sure to load this before all the other start plugins
-- 	config = function()
-- 		-- load the colorscheme here
-- 		require("night-owl").setup()
-- 		vim.cmd.colorscheme("night-owl")
-- 	end,
-- }
